name: Manage Assets

on:
  schedule:
    - cron: '5 23 * * *'   # 23:05 GMT = 00:05 BST
  workflow_dispatch:
    inputs:
      app_list:
        description: 'Comma-separated app names (leave empty for all)'
        required: false
        type: string

jobs:
  manage-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install pillow python-dotenv

    - name: Run asset management
      env:
        APP_LIST: ${{ inputs.app_list }}
      run: |
        if [ "${{ github.event_name }}" = "schedule" ]; then
          python3 scripts/manage_assets.py
        elif [ -n "$APP_LIST" ]; then
          python3 scripts/manage_assets.py --apps "$APP_LIST"
        else
          python3 scripts/manage_assets.py
        fi
          
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Apps/
        git commit -m "chore: Update assets for ${{ inputs.app_list || 'all apps' }}" || echo "No changes to commit"
        git push
