name: Scrape Icons

on:
  workflow_dispatch:
    inputs:
      app_list:
        description: 'Comma-separated app names (leave empty for all)'
        required: false
        type: string

jobs:
  scrape-icons:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install pillow requests

    - name: Run icon scraper
      env:
        APP_LIST: ${{ inputs.app_list }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -n "$APP_LIST" ]; then
          python3 scripts/scrape_icons.py --apps "$APP_LIST"
        else
          python3 scripts/scrape_icons.py
        fi

    - name: Convert iOS-optimized PNGs
      run: python3 scripts/convert_ios_pngs.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Apps/
        git commit -m "chore: Update icons for ${{ inputs.app_list || 'all apps' }}" || echo "No changes to commit"
        git push 